name: Hola mundo

on: 
  push: 
    branches: [main]

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hola mundo desde GitHub Actions"
      - run: echo "Este es un ejemplo de un workflow simple"
      - run: echo "¡Listo para desplegar!"
  
  second-job:
    runs-on: ubuntu-latest
    needs: first-job
    steps:
      - run: echo "Este es el segundo trabajo"
      - run: echo "Aquí puedes agregar más pasos para tu flujo de trabajo"
      - run: echo "¡Todo listo!"