name: Hola mundo

on:
  push:
    branches: [main]

jobs:
  first-job:
    runs-on: ubuntu-latest
    env:
      NAME: Primmera variable Prueba
    steps:
      - run: echo "Hola mundo desde GitHub Actions"
      - run: echo "Este es un ejemplo de un workflow simple"
      - run: echo "¡Listo para desplegar!"
      - run: echo "Variable de entorno $NAME"

  second-job:
    if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/release'}}
    runs-on: ubuntu-latest
    needs: first-job
    steps:
      - run: echo "Este es el segundo trabajo"
      - run: echo "Aquí puedes agregar más pasos para tu flujo de trabajo"
      - run: echo "¡Todo listo! ${{ github.event_name }}"

  checkout-job:
    runs-on: ubuntu-latest
    steps:
      - name: Working Dir
        run: ls -la

      - name: Action [Checkout]
        uses: actions/checkout@v4

      - name: Working Dir after checkout
        run: ls -la

  sharing-between-steps:
    runs-on: ubuntu-latest
    steps:
      - name: Output a variable
        id: step-1
        run: echo "variable=Hola mundo" >> $GITHUB_OUTPUT
      
      - name: Read a variable
        run: 'echo "Variable del step 1: ${{ steps.step-1.outputs.variable }}"'

  sharing-between-jobs:
    runs-on: ubuntu-latest
    outputs:
      output-1: ${{ steps.step-1.outputs.variable }}
      output-2: ${{ steps.step-2.outputs.variable }}
    steps:
      - name: Output a variable
        id: step-1
        run: echo "variable=Hola mundo" >> $GITHUB_OUTPUT
      - name: Output another variable
        id: step-2
        run: echo "variable=Adiós mundo" >> $GITHUB_OUTPUT

  sharing-between-jobs-2:
    runs-on: ubuntu-latest
    needs: sharing-between-jobs
    env:
      VARIABLE_1: ${{ needs.sharing-between-jobs.outputs.output-1 }}
      VARIABLE_2: ${{ needs.sharing-between-jobs.outputs.output-2 }}
    steps:
      - name: Read a variable from another job
        run: |
          echo "Variable del step 1: $VARIABLE_1"
          echo "Variable del step 2: $VARIABLE_2"

  generate-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Create a file
        run: echo "Este es un archivo de ejemplo" > example.txt

      - name: Upload artifact
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: archivo-test
          path: example.txt
          if-no-files-found: error
    
  download-artifact:
    runs-on: ubuntu-latest
    needs: generate-artifact
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: archivo-test

      - name: List files
        run: ls -la

      - name: Read the file
        run: cat example.txt

  matrix_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        message: ["Hola", "Mundo", "GitHub Actions"]
    steps:
      - name: Print message
        run: echo "Running on ${{ matrix.os }}"