name: Deploy

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: setup
        if: success()
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        if: success()
        run: npm install

      - name: Run tests
        if: success()
        run: npm run test

  deploy:
    if: success()
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy
        run: echo "Deploy..."