name: Publicar paquete en Github Packages

on:
  push:
    branches:
      - main

jobs:
  publicar-paquete:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      # La acción setup-node@v4 crea un archivo .npmrc en el runner para publicar en GitHub Packages.
      # Usa como referencia el token de la variable de entorno NODE_AUTH_TOKEN (GITHUB_TOKEN en realidad).
      - name: Configurar Node.js y .npmrc
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@stratos-code'

      - name: Instalar dependencias
        run: npm ci

      - name: Publicar paquete en GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}